### ISSUE TITLE
SHM: dramatically slowdown 

### ISSUE THREAD

**Issue by geraldus** [chrisdone/structured-haskell-mode#101]
I'm not certain about it, but looks like if there are shakespearen templates embedded in haskell code __SHM__ slows down dramatically, sometimes freezing Emacs. I've noticed this several times, actual issue could be related to any quasi—quotes, but again I'm not certain about.
I've tried to disable other plugins when I've faced speed regression last time (e.g. ido, flx …), but only SHM was responsible for regression and freezes.

I have GNU Emacs 24.4.2 (x86_64-apple-darwin14.1.0, Carbon Version 157 AppKit 1344.72)
SHM installed from Git [a1552af3555af62643731864ec16ce524c2de6a8]

**Comment by chrisdone** [comment]
This seems fine:
``` haskell
x = do [whamlet|foosdfsdf |]
       case [whamlet|foosdfsdf |] of
         _ -> [whamlet|foosdfsdf |]
       [whamlet|foosdfsdf |]
```
How… *big* is your declaration?

**Comment by geraldus** [comment]
About 10-20 lines on hamlet for example, when I write templates I start with small embeded hamlet quasiquotes, and when first design is finished I move template code to separate file. I've noticed that slowdown usually occurs when my code have embeded templates. But again, I'm not certain. I'll try to reproduce issue tomorrow.

**Comment by geraldus** [comment]
I've recorded small video demonstrating issue. Here it is:

http://www.youtube.com/watch?v=A7Yem4pYScY&feature=youtu.be

If you need additional information _(Emacs and plugin versions etc.)_ please let me know.
Sorry, it took ages me to record this. Hope this will help. Have a nice day!

**Comment by chrisdone** [comment]
From the video I can see that SHM cannot parse your declaration, see your minibuffer has `SHM!` in it. This means it's re-parsing the declaration and failing every key press. Normally, SHM only re-parses on an idle timer.

I recently fixed parsing of quasi quotes, which was a recent regression. So I'd try updating your `structured-haskell-mode` executable.

**Comment by geraldus** [comment]
Well, I've made `git pull` and rebuilt SHM. Not it looks like slowdown issue gone! Cool!
I'll close this for now.
By the way, SHM still prepends newlines within quasi quote with `,` commas. Is it known issue or I have something wrong in my configuration.

_P.S._ I have several questions about SHM, is it normal to create issues to ask them, or should I use ask minor questions somewhere else? Thank you for amazing stuff like SHM.

**Comment by chrisdone** [comment]
Issues are best.
