### ISSUE TITLE
SHM: smh/newline-indent insert wrong amount of spaces

### ISSUE THREAD

**Issue by geraldus** [chrisdone/structured-haskell-mode#102]
I have configured __SHM__ to use four spaces as basic indentation unit:

```elisp
(setq shm-indent-spaces 4)
```

However, <kbd>C-j</kbd> inserts only two spaces. Looks like this variable does not appears in my easy customisations section of `.emacs`, so I'm confused, maybe there is exists another variable or something affecting amount of spaces when indenting?

**Comment by chrisdone** [comment]
I think it may be using `haskell-indent-spaces` if that is defined.

**Comment by geraldus** [comment]
You're right, I have `haskell-indent-spaces` set to `2`. Thanks, Chris!
