### ISSUE TITLE
Keystroke to find and bring up attached REPL

### ISSUE THREAD

**Issue by rrnewton** [chrisdone/structured-haskell-mode#107]
I just tried SHM again and switched to it for good this time -- it's fantastic!

One thing I find myself doing a lot is opening various Haskell files from different projects/.cabal files and having multiple REPLs open.  For various reasons I then lose the two-frame layout with the REPL and I have to get it back.

I've been doing this restore operation manually, but it would be really fantastic to have a keystroke that:

 * Finds which project is associated with the current buffer
 * Switches to a layout showing the REPL below
 * (optionally) Switches focus to the REPL (because I usually do this when I want to actually type something at the REPL)

This can probably be done with just a tiny bit of emacs code in my `.emacs`, but could I get a tip on how to accomplish the first step above?  Thanks.

**Comment by ivan-m** [comment]
I have this in my .emacs config:

```.emacs
(define-key haskell-mode-map [?\C-c ?\C-z] 'haskell-interactive-switch)
```

Note that it isn't SHM-specific.  You can find other example keybindings here: https://github.com/chrisdone/emacs-haskell-config

**Comment by rrnewton** [comment]
Awesome, thanks!  (Hah, I already had the keystroke bound actually because I'm using Chris's `emacs-haskell-config`.  RTFM indeed.)
