### ISSUE TITLE
please gpg sign tags and commits

### ISSUE THREAD

**Issue by thkoch2001** [chrisdone/structured-haskell-mode#109]
It would make it much easier to try and trust structured-haskell-mode if you could be so kind and sign at least the git tags and maybe also the commit. Just add to your git config:

```
[user]
    signingkey = 9616E227 # this is the key I found for chrisdone
[commit]
    gpgsign = true
```

Could you also get more people to sign your key? - Thank you!

**Comment by chrisdone** [comment]
Nope
