### ISSUE TITLE
Why isn't this on Melpa or another package repo?

### ISSUE THREAD

**Issue by bsima** [chrisdone/structured-haskell-mode#112]
`package.el` is pretty nice, I wish I could do `M-x package-install RET structured-haskell-mode RET` instead of manually installing. Is there a reason that this isn't in Melpa or Marmalade?

**Comment by ivan-m** [comment]
It is on Melpa, called `shm` (but you need to install the executable from Hackage).

**Comment by bsima** [comment]
Ooohh, okay thanks!
