### ISSUE TITLE
Lambdas in interactive mode

### ISSUE THREAD

**Issue by ivan-m** [chrisdone/structured-haskell-mode#119]
With `structured-haskell-repl-mode` on, when I try and use a lambda function something weird happens.  Starting here (with the cursor right after the `|`):

```
λ> \
```

Hitting space, I would expect:

```
λ> \_ -> undefined
```

With the cursor over the `_` and both it and `undefined` in `shm-evaporate-face`.

However, what actually happens is:

```
λ> undefined\ -> 
```

(with a space at the end of the line) where only `ined` is in `shm-evaporate-face`.

**Comment by chrisdone** [comment]
Not supporting HIM anymore.

**Comment by ivan-m** [comment]
HIM ? Do you mean SHM?

**Comment by chrisdone** [comment]
Haskell-interactive-mode
