### ISSUE TITLE
`shm/newline-indent-proxy` do not work.

### ISSUE THREAD

**Issue by Gnouc** [chrisdone/structured-haskell-mode#123]
I took this from haskell.org:
```
primes = filterPrime [2..] 
  where filterPrime (p:xs) = 
          p : filterPrime [x | x <- xs, x `mod` p /= 0]
```

When I type as normal:
```
primes = filterPrime [2..<cursor>]
```
press `)`
```
primes = filterPrime [2..]<cursor>
```
press `C-j`, then the cursor was placed at the start of next line:
```
primes = filterPrime [2..]
<cursor>
```
instead of two spaces indentation:
```
primes = filterPrime [2..]
  <cursor>
```
How can I archive the intended indentation?

Here is my [haskell config](https://github.com/Gnouc/emacs.d/blob/master/init.el#L474). If I replace `'structured-haskell-mode` with `'turn-on-haskell-indentation`, then everything work well.

**Comment by ocharles** [comment]
I think there is a binding to jump to where clauses, which is probably what
you want in this case

**Comment by cocreature** [comment]
Do you have electric-indent-mode turned on? Iirc it’s on by default since emacs 24.4 and in the case of shm it switches the meaning of C-j and Return, so you need to press return if you want the “intelligent” indentation.

**Comment by Gnouc** [comment]
@cocreature I actually have `electric-indent-mode` enable, and using enter now work well.

Before opening the issue, I also try `RET` but did not get the intended indentation, I re-checked and see that the error in my file so indentation did not work.

Thanks guys for the help.
