### ISSUE TITLE
Problems wrapping with double quotes

### ISSUE THREAD

**Issue by acowley** [chrisdone/structured-haskell-mode#130]
Example:
```
foo = |-DPYTHON_LIBRARY=
```

(Point at the "|")

Press `C-M-<space>` to mark the node, then press `"`. Alternately, mark the text using usual emacs region stuff and press `"`.

Expected:
```
foo = "-DPYTHON_LIBRARY="
```

Actual:
```
foo = ""-DPYTHON_LIBRARY=
```

**Comment by chrisdone** [comment]
I think your example is a parse error. So `C-M-<space>` in the presence of a parse error does nothing.

**Comment by acowley** [comment]
It looks like it marks it, but you can also just do a normal `C-<space> C-e` to mark it. I do think the problem is a parse error, but perhaps when a region is active shm could ignore the parse error and wrap the region.

**Comment by acowley** [comment]
Oh, because I know the easy answer is to not type it like that, I got myself into this position when I wanted to break a string literal into parts.

**Comment by chrisdone** [comment]
Okay, paredit has `paredit-split-sexp` for that. I've been using that. I'll implement something similar for SHM.

**Comment by chrisdone** [comment]
Implemented `shm/split`. Like `paredit-mode`, it's available under the key `M-S`.
