### ISSUE TITLE
List-ish shm/newline-indent

### ISSUE THREAD

**Issue by acowley** [chrisdone/structured-haskell-mode#131]
This is perhaps just a "that's the way it is" thing, but I can't seem to figure out a good way to type lists.

Given,
```
foo = [subtract 1|]
```

(point at `|`)

I'd like to be able to hit `C-j` and get
```
foo = [subtract 1
      ,|]
```
Instead, I get
```
foo = [subtract 1
                |]
```

I understand the intent there, but is there a way to let shm know I want a new list item rather than the opportunity to supply another argument? If not, how can I best enter the next list item given where I'm left?

If I do a kind of manual ANF transform so I only have lists of atoms, the list indentation does something a bit odd given my preferred indentation style:

Given,
```
foo = [ x|]
```

hitting `C-j` results in,
```
foo = [ x
      ,  |]
```

Note that point is one character too far to the right. Perhaps this indentation style isn't supported, but the behavior is so close to working, I thought I'd mention it in case it's salvageable.

**Comment by cocreature** [comment]
You just need to select the `subtract 1` node instead of `1` by calling `shm/close-paren` bound to `)` by default. That gives you exactly what you want.

**Comment by acowley** [comment]
Thanks @cocreature, that's exactly what I wanted!
