### ISSUE TITLE
New HSE works great

### ISSUE THREAD

**Issue by acowley** [chrisdone/structured-haskell-mode#134]
This is not so much an Issue but a note:

I bumped the resolver to `lts-6.9` and added `haskell-src-exts-1.18.2` as an `extra-dep`. I had to change the import in `Main.hs`  to just `Language.Haskell.Exts`, and everything works. This was important to me as node navigation was broken in the presence of newer language extensions (e.g. `TypeApplications`), but it now works reliably.

Presumably `hse-1.18.x` will be included in LTS 7, so bumping the resolver in the `stack.yaml` at that point will be helpful.

**Comment by chrisdone** [comment]
Oki doki. I won't be getting around to this soon.
