### ISSUE TITLE
new stack install fails on compiling structured-haskell-mode ("applicative-quoters")

### ISSUE THREAD

**Issue by jowens** [chrisdone/structured-haskell-mode#135]
This is on OS X, stack installed via homebrew. Never done this before. Please help me provide debug info! I was able to install every other executable I needed from here (https://github.com/serras/emacs-haskell-tutorial/blob/master/tutorial.md) except structured-haskell-mode.

```
$ stack --version
Version 1.1.2 x86_64 hpack-0.14.0
```

```
$ stack install structured-haskell-mode
Run from outside a project, using implicit global project config
Using resolver: lts-6.10 from implicit global project's config file: /Users/jowens/.stack/global-project/stack.yaml
While constructing the BuildPlan the following exceptions were encountered:

--  While attempting to add dependency,
    Could not find package applicative-quoters in known packages

--  Failure when adding dependencies:
      applicative-quoters: needed (-any), stack configuration has no specified version (latest applicable is 0.1.0.8)
      haskell-src-exts: needed (==1.16.*), 1.17.1 found (latest applicable is 1.16.0.1)
    needed for package structured-haskell-mode-1.0.20

Recommended action: try adding the following to your extra-deps in /Users/jowens/.stack/global-project/stack.yaml
- applicative-quoters-0.1.0.8

You may also want to try the 'stack solver' command
```

**Comment by FrancisMurillo** [comment]
I had somewhat the same issue when installing it with `stack`. What I did is configure my `~/.stack/global-project/stack.yaml` of the line from
`extra-deps: []`
to
`extra-deps: [applicative-quoters-0.1.0.8, haskell-src-exts-1.16.0.1]`
and it pretty much installs afterwards.

What bothers me with how I did it is if this is how it really is supposed to be installed? Would like to hear more.

**Comment by cocreature** [comment]
Just build from git master, the dependency on `applicative-quoters` has been removed.

**Comment by jowens** [comment]
Is there a way to do a github-sourced install from within stack? (Apologies for being a stack n00b.) `stack --install-from-github install structured-haskell-mode`, that sort of thing?

**Comment by conal** [comment]
I asked the same question on the #haskell-stack IRC room and learned that there is indeed a way. See [this example](https://gist.github.com/bitemyapp/38b9ae998e2c1101becd3dc0dc7f68b0) and [this one](https://github.com/conal/reification-rules/blob/master/stack.yaml).

**Comment by jowens** [comment]
It was not 100% clear to @conal and me if it was possible to do this by editing a file *only* in ~/.stack (as opposed to manually downloading and building structured-haskell-mode standalone). I noted to him:

> In an ideal world, what I think I should do is somewhere in ~/.stack I need to put a pointer to the github version to override some sort of default that's pointing to some other version. In that ideal world, I shouldn't have to manually download anything. stack install should take care of the download and build for me, if only I tell it where to look (not the default).

Might be something I can add to `~/.stack/global-project/`, dunno. Advice appreciated.

**Comment by jowens** [comment]
Just noting a couple of months later that stack continues to have the same version and thus the same problem. Any plans to release the git master version to stack?

**Comment by jowens** [comment]
Still hoping the git master version goes to stack at some point.

**Comment by acowley** [comment]
I bumped the version and resolver and tagged the commit. Just need @chrisdone to do the push!

**Comment by jowens** [comment]
@chrisdone, any possibility of this push?

**Comment by chrisdone** [comment]
Oh, thanks for the bump. I'll push to hackage.

**Comment by chrisdone** [comment]
Bumped to hackage.

**Comment by jowens** [comment]
@chrisdone Noting that (at least with current stack, best I can tell) this is still broken.

```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for structured-haskell-mode-1.1.0:
    haskell-src-exts-1.17.1 must match >=1.18 (latest applicable is 1.19.1)
```

**Comment by jowens** [comment]
@chrisdone Sadly, this still seems to be broken (same message as above).

**Comment by acowley** [comment]
@jowens What stackage resolver are you using? Current [LTS](https://www.stackage.org/lts-8.13) contains `haskell-src-exts-1.18.2` which should work, so we need to figure out where that `1.17.1` constraint you're seeing is coming from.

**Comment by jowens** [comment]
The answer is "the default", which appears to be:
```
$ grep resolver ~/.stack/global-project/stack.yaml
resolver: lts-7.16
```

**Comment by acowley** [comment]
There isn't a canonical "default" for stackage or stack, so perhaps this is something that got set up the last time you installed stack. If you bump that resolver up to the 18 series, you should get a sufficiently new `haskell-src-exts`.

**Comment by jowens** [comment]
Super. What do you recommend as something that you think would generally work (across numerous packages)?

**Comment by acowley** [comment]
You can take a look at what's included in the package sets at the [stackage](https://www.stackage.org/) web page. The considerations are what version of GHC is associated with the package set, and that, when there is a major version bump in the package set itself, some packages may be left behind for a short time. For now, going to the current LTS release, 8.13, should be okay as long as you are okay with using GHC-8.0.2 (you are currently using 8.0.1 given your resolver setting).

**Comment by jowens** [comment]
Thank you for this guidance! lts-8.13 worked flawlessly with every package I upgraded, and this one as well. I'm gonna call this a win!

**Comment by jowens** [comment]
(I did not know this was something I needed to manually update, but now, I'm good!)

**Comment by acowley** [comment]
Great news, @jowens!
