### ISSUE TITLE
One off-topic question though: What's the color theme in the examples on README?

### ISSUE THREAD

**Issue by linktohack** [chrisdone/structured-haskell-mode#136]
Thanks

**Comment by ivan-m** [comment]
I think @chrisdone uses [Zenburn](https://github.com/chrisdone/chrisdone-emacs/blob/bda21f937ae128c85b3f0fe992a6c3b442e7b555/init.el#L11).

**Comment by linktohack** [comment]
Thanks @ivan-m, closing!
