### ISSUE TITLE
How to disable haskell-indention-mode?

### ISSUE THREAD

**Issue by peti** [chrisdone/structured-haskell-mode#138]
The documentation says that one is supposed to disable haskell-mode's indentation features, but how exactly do I do that? It seems to me like haskell-mode enables those features unconditionally?

**Comment by chrisdone** [comment]
In the haskell-mode docs it talks about enabling indentation modes.

**Comment by peti** [comment]
I saw the sections in the manual about enabling indention modes ... but I saw nothing about how to enable no indention mode at all, which is what `structured-haskell-mode` needs, no?

**Comment by ivan-m** [comment]
Just don't specify one in your `haskell-mode-hook`?

**Comment by peti** [comment]
@ivan-m, then I'll get the default indention mode.

**Comment by ivan-m** [comment]
@peti `M-x customize-variable haskell-mode-hook` and make sure the hooks are disabled?

**Comment by peti** [comment]
@ivan-m, I had no idea this possibility existed.

**Comment by ivan-m** [comment]
@peti: and now you do :)
