### ISSUE TITLE
The gifs in the github readme view are broken

### ISSUE THREAD

**Issue by robgssp** [chrisdone/structured-haskell-mode#149]
All the animations for the editor actions are broken links now.

**Comment by ccressent** [comment]
Some of the gifs, but not all of them, appear to have moved here recently:
http://chrisdone.com/structured-haskell-mode/gifs/

All of them also appear to be in the repo's `gifs/` directory.

@chrisdone: which gifs should we use? This is an easy fix and I can submit a PR for it if you want.

**Comment by ivan-m** [comment]
@ccressent make them use the `gifs/` directory and I'll approve the pull request.
