### ISSUE TITLE
Compilation problem when installing structured-haskell-mode

### ISSUE THREAD

**Issue by james-elliot** [chrisdone/structured-haskell-mode#155]
I have installed ghc (version 8.0.2) and cabal (version 1.24.2) with the debian packages in sid, and I have been installing all other haskell packages directly from hackage using cabal.
When I try to install structured-haskell-mode I get this compilation error:
[structured-haskell-mode-1.1.0.log](https://github.com/chrisdone/structured-haskell-mode/files/1638879/structured-haskell-mode-1.1.0.log)

**Comment by ivan-m** [comment]
Closing in favour of #156
