### ISSUE TITLE
Comment at the end of a line breaks indentation

### ISSUE THREAD

**Issue by boothead** [chrisdone/structured-haskell-mode#19]
Came across this with applicative syntax:

``` haskell
some <$> test
     <*> one
     <*> two -- breaking comment

aList = [one
        ,two
        ,three -- ok
        ,four]
```

The first comment breaks `C-j` to add a new line and indent. With my cursor at the end of the word comment nothing is highlighted and C-j does nothing. If I move the cursor back to `two` `C-j` adds and indents a new line like this `<*> _ -- breaking comment`. The list was fine (I was able to `C-j` and then insert `four`

**Comment by chrisdone** [comment]
Probably not going to get round to this.
