### ISSUE TITLE
Should do something with C preprocessor lines 

### ISSUE THREAD

**Issue by rrnewton** [chrisdone/structured-haskell-mode#22]
When editing a file with CPP, it gets confused where the `#if` starts and gives me one of these (via `shm/test-exe`): 

```
structured-haskell-mode: Parse error: Last statement in a do-block must be an expression
```

Or one of these:

```
structured-haskell-mode: Parse error: #
```

I'm not sure what a good solution actually is though...

**Comment by chrisdone** [comment]
Not likely to get round to this.
