### ISSUE TITLE
Context of a function does not form a node

### ISSUE THREAD

**Issue by ocharles** [chrisdone/structured-haskell-mode#5]
If I have the following:

``` haskell
foo :: Eq a => a -> a
```

I may later want to add more constraints to the context of this function. I would like to move the point over `Eq a` and use `)` to select the whole `Eq a` node and then surround it with parenthesis (`M-(`). Unfortunately, the node selected is `Eq a =>`, which is too large a selection,

**Comment by chrisdone** [comment]
I don't think I'll get round to this issue.
