### ISSUE TITLE
Can't get it working - Install problems?

### ISSUE THREAD

**Issue by fosskers** [chrisdone/structured-haskell-mode#64]
Hi, awesome mode! I'm trying to make an Arch Linux package for it, but I can't seem to get it working. 

I have the executable located at: `/usr/bin/structured-haskell-mode` and all the `.el*` files located in `/usr/share/emacs/site-lisp/structured-haskell-mode/`.

My `.emacs` has the following lines:

``` elisp
(add-to-list 'load-path "/usr/share/emacs/site-lisp/structured-haskell-mode")
(require 'shm)
(add-hook 'haskell-mode-hook 'structured-haskell-mode)
```

No matter what I sort of Haskell I type into emacs, it gives me `SHM!` in the bottom bar.  Upon trying `M-x shm/test-exe` I'm given nothing but a blank buffer. `M-x shm-test/run-all` opens a new buffer with:

``` haskell
foo bar baz =
     bar + baz
```

and tells me "End of file during parsing".

I'm kind of at a loss here. Any idea of what the problem might be?

**Comment by stevemasta34** [comment]
I'm having a similar problem, but I don't see anyone else on the net having the problem

**Comment by ivan-m** [comment]
@stevemasta34 is the shm executable in your PATH?  Check what emacs thinks the PATH is with `(getenv "PATH")`.

**Comment by fosskers** [comment]
I tried this again today and got it working, but usage itself is buggy enough to hamper workflow.
