### ISSUE TITLE
Turn off haskell-indentation-modes.

### ISSUE THREAD

**Issue by danielsz** [chrisdone/structured-haskell-mode#69]
It would be nice to have an emacs lisp code snippet in the README to illustrate how to turn off haskell-indentation-modes for people like me for whom it is not obvious. Thank you.

**Comment by adamcavendish** [comment]
It seems that the link has changed. 
http://haskell.github.io/haskell-mode/manual/latest/Indentation.html

But the page did not tell us how we might turn off the `haskell-indentation-modes`. Maybe you should write a Q&A on this. Thx. @chrisdone

**Comment by adamcavendish** [comment]
I figured out that the following config works. Maybe we should put it in the README

```
    (require 'shm)
    (when (fboundp 'haskell-indentation-mode)
      (haskell-indentation-mode -1))
    (add-hook 'haskell-mode-hook 'structured-haskell-mode)
```
