### ISSUE TITLE
Don't parse with all extensions enabled at all times

### ISSUE THREAD

**Issue by sergv** [chrisdone/structured-haskell-mode#70]
Hi, sometimes parsing seems to fail even when ghc would happily compile file. For example, in my file I have

``` haskell
f rec x = do
  y <- g x
  rec y
```

and recursive do extension is not enabled, so ghc accepts file while shm flags this code as errorneous.

Conversely, shm may happily parse GADT definition even when relevant extension is not enabled in file.

Therefore I propose to detect which extensions are specified in file LANGUAGE pragmas and passing them to structured-haskell-mode executable. Of course extensions can be specified in cabal files or on ghc command line so detecting them becomes harder, but maybe it's still a good idea to try?

**Comment by chrisdone** [comment]
I've changed extensions to match hlint's default extensions which excludes Arrows and recursive do. Now the executable can be passed additional arguments to enable or disable extensions:

    $ structured-haskell-mode 
    structured-haskell-mode: (parse|check) (decl|stmt) [-X<...>]*
    $ echo 'proc rec = return ()' | structured-haskell-mode parse stmt
    structured-haskell-mode: parseImport
    $ echo 'proc rec = return ()' | structured-haskell-mode parse decl
    [["Decl SrcSpanInfo" FunBind 1 1 1 21]["Mat…
    $ echo 'proc rec = return ()' | structured-haskell-mode parse decl -XArrows
    structured-haskell-mode: Parse error: rec
    $ echo 'proc rec = return ()' | structured-haskell-mode parse decl -XArrows -XNoArrows
    [["Decl SrcSpanInfo" FunBind 1 1 1 21]["Mat…
