### ISSUE TITLE
Evil incompatibility

### ISSUE THREAD

**Issue by ian-mi** [chrisdone/structured-haskell-mode#81]
When using evil + shm with minimal configuration, most of shm does not appear to work correctly. For example if I write

f = foo bar

and I move my cursor so that bar is the current node and type C-j in order to make a new sibling, bar is split at the cursor position, for example

f = foo b
           ar

Is it possible to configure evil to work with shm?

edit: github ate my whitespace here, but ar should be aligned with b.

edit: My .emacs config:
(require 'evil)
(require 'shm)

(evil-mode 1)

(add-hook 'haskell-mode-hook 'structured-haskell-mode)

**Comment by ts468** [comment]
@ian-mi, did you have any success in getting shm to work with evil? If so, would you maybe have a minimal example that shows how to set it up?

**Comment by EDmitry** [comment]
Structured haskell mode works fine in insert mode in evil. You have to add certain key bindings for normal mode though. I am still working on this and will update with more info on this. There is one extremely annoying thing in haskell-mode: evil calls `indent-according-to-mode` often and it always opens the window asking to set an indentation mode. One way to deal with this is to reimplement every evil function for SHM so that it doesn't call indent-according-to-mode, but that's just an overkill. I wish there was a way to just disable that in haskell-mode itself (https://github.com/haskell/haskell-mode/issues/290)

**Comment by srhb** [comment]
Is this not a problem with how haskell-mode handles indentation? It seems the whole hook-based-with-warnings system is completely incompatible with the assumptions evil makes (that works for every other package out there)

**Comment by EDmitry** [comment]
Evil doesn't make any weird assumptions. It just tries to reindent much more often, that's all.

**Comment by unhammer** [comment]
`                 (setq evil-auto-indent nil)` at least gets rid of the warnings, although you then have to press TAB after `o`. I ended up defining


    (defun evil-shm/open-above (count)
      "Insert a new line above point and switch to Insert state.
    The insertion will be repeated COUNT times."
      (interactive "p")
      (back-to-indentation)
      (save-excursion (shm/newline-indent))
      (setq evil-insert-count count
            evil-insert-lines t
            evil-insert-vcount nil)
      (evil-insert-state 1)
      (add-hook 'post-command-hook #'evil-maybe-remove-spaces))
    
    (defun evil-shm/open-below (count)
      "Insert a new line below point and switch to Insert state.
    The insertion will be repeated COUNT times."
      (interactive "p")
      (goto-char (line-end-position))
      (shm/newline-indent)
      (setq evil-insert-count count
            evil-insert-lines t
            evil-insert-vcount nil)
      (evil-insert-state 1)
      (add-hook 'post-command-hook #'evil-maybe-remove-spaces))

      (evil-define-key 'normal shm-map
                   (kbd "O") #'evil-shm/open-above
                   (kbd "o") #'evil-shm/open-below)

**Comment by korayal** [comment]
is there any hope on having this fixed?

**Comment by sooheon** [comment]
I don't see what the problem is. The given case does not reproduce for me, (with `-Q` and @ian-mi 's config) with cursor in normal mode over `b` in `bar`, `C-j` brings `bar` down to next line. Obviously, in insert state, everything works exactly as intended as well.
